using TinyEvents.SourceGen.Emission.Writing;
using TinyEvents.SourceGen.Planning;

namespace TinyEvents.SourceGen.Emission;

internal static class ThisAssemblyContributionEmitter
{
    public static string Emit(TinyEventsGenerationPlan plan)
    {
        var writer = new SourceWriter();

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("#nullable enable");
        writer.WriteLine("namespace TinyEvents.Generated");
        writer.WriteLine("{");
        writer.Indent();

        ConsumerRegistrationEmitter.Emit(writer, plan);
        writer.WriteLine();
        ModuleInitializerEmitter.Emit(writer);

        writer.Unindent();
        writer.WriteLine("}");

        return writer.ToString();
    }
}
